language: php

matrix:
  include:
    - php: 7.1
    - php: 7.2
      env: QA=yes
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - composer selfupdate
  - |
    if [ "$QA" == "yes" ]; then
      composer require 'satooshi/php-coveralls:*'
    else
      composer install
    fi

script:
  - composer travis

after_success:
  - if [ "$QA" == "yes" ]; then travis_retry php vendor/bin/php-coveralls -v; fi
